import './style.css';

const base = import.meta.env.BASE_URL;

const buildings = [
  { no: '01', title: '上海中心大厦', type: '实证 + 推断复原 · 超高层', detail: '实色为已证实的九个垂直社区、双层幕墙公共区与空中花园；浅色排线为按外形与用途约束复原的核心筒和标准楼板，不代表真实平面。', image: `${base}images/01-shanghai-tower-inference.png`, sources: [['上海中心官网', 'https://www.shanghaitower.com/community.html'], ['上海市国资委', 'https://www.gzw.sh.gov.cn/shgzw_zxzx_gqdt/20240627/92d965292cb24ce0ab1cc0223700796d.html']] },
  { no: '02', title: '东方明珠', type: '实证 + 推断复原 · 观光塔', detail: '实色为公开资料可核的球体、观光层、旋转餐厅与双轿厢电梯关系；浅色排线复原球体内的通用径向楼板与服务空间，不是技术图纸。', image: `${base}images/02-oriental-pearl-inference.png`, sources: [['东方明珠运营方', 'https://www.opg.cn/cn/newsCenter/newsInfo/1542348219159158784.html'], ['Otis 项目资料', 'https://www.otis.com/zh/cn/our-company/global-projects/project-showcase/oriental-pearl-tower']] },
  { no: '03', title: '中华艺术宫', type: '实证 + 推断复原 · 美术馆', detail: '实色为 0m、33m、41m、49m、60m 的公开功能层级及巨柱、悬挑、斜撑；浅色排线是受这些高程与结构约束的展厅楼板与竖向联系复原。', image: `${base}images/03-china-art-museum-inference.png`, sources: [['上海市政府', 'https://www.shanghai.gov.cn/nw9822/20200906/0001-9822_653206.html'], ['同济大学', 'https://ddms.tongji.edu.cn/18/62/c13236a137314/page.htm']] },
  { no: '04', title: '徐家汇圣依纳爵主教座堂', type: '实证 + 推断复原 · 哥特复兴', detail: '实色为拉丁十字平面、三通廊、尖拱、束柱、祭坛、唱诗楼与彩窗；浅色排线补足屋架、座椅和不可见支承。', image: `${base}images/04-xujiahui-cathedral-inference.png`, sources: [['徐汇档案馆', 'https://www.xuhui.gov.cn/xhda/xhda/xhbl/xhnj/2019/08/27/9f8086926cbda259016cd1aa7d45154b.html?tm=1740650443068'], ['徐汇区政府', 'https://www.xuhui.gov.cn/xwzx_bmlf/20230413/514234.html']] },
  { no: '05', title: '摩西会堂', type: '实证 + 推断复原 · 犹太遗产', detail: '实色为三层外廊、红砖斜顶、马赛克地坪、木扶手及修缮中的约柜；浅色排线只补足常规楼板与未见空间。', image: `${base}images/05-ohel-moishe-inference.png`, sources: [['上海市政府', 'https://www.shanghai.gov.cn/nw4411/20240506/499b9bce629e44e589e2a3392fda69c6.html'], ['上海犹太难民纪念馆', 'https://www.shhkjrm.com/info/1011/3811.htm']] },
  { no: '06', title: '上海音乐厅', type: '实证 + 推断复原 · 海派古典', detail: '实色为镜框式舞台、穹顶、柱式、吊灯与水磨石等修缮要素，以及整体平移的空间故事；浅色排线为扩建部分的谨慎复原。', image: `${base}images/06-shanghai-concert-hall-inference.png`, sources: [['上海院', 'https://www.siadr.com/projectdetails/5d9f34b9e4d1cc023747fd80/'], ['上海文旅推广网', 'https://www.meet-in-shanghai.net/cn/news/the-renovation-of-the-shanghai-concert-hall-was-completed-and-reopened-on-september-6-256543/']] },
  { no: '07', title: '上海交响乐团音乐厅', type: '实证 + 推断复原 · 声学工程', detail: '实色为大小音乐厅、地下体量、隔振器、混凝土支墩和“房中房”声学外壳；浅色排线仅复原日常附属空间。', image: `${base}images/07-shanghai-symphony-hall-inference.png`, sources: [['文化和旅游部', 'https://www.mct.gov.cn/whzx/qgwhxxlb/sh/201409/t20140909_781644.htm'], ['上海建工', 'https://www.scg.com.cn/scg_mtbd/2013-02-24/Detail_199628.htm']] },
  { no: '08', title: '龙美术馆西岸馆', type: '实证 + 推断复原 · 工业遗产', detail: '实色为北票码头煤漏斗、清水混凝土“伞拱”与主要展厅；浅色排线只补足未公开的展墙、机电与动线。', image: `${base}images/08-long-museum-west-bund-inference.png`, sources: [['西岸', 'https://www.westbund.com/cn/index/Visitors_guide/Location/Long-Museum-West-Bund.html'], ['上海市文旅局', 'https://whlyj.sh.gov.cn/gqfc/20250521/6cd8a6e351814965b9b5f1cd515994d6.html']] },
  { no: '09', title: '上海油罐艺术中心', type: '实证 + 推断复原 · 工业改造', detail: '实色为航油罐、圆形穹顶、通高展厅、覆土连接面和三层罐体；浅色排线仅描写合理但未被图纸证实的楼梯和展墙。', image: `${base}images/09-tank-shanghai-inference.png`, sources: [['上海市文旅局', 'https://whlyj.sh.gov.cn/gqfc/20250521/6cd8a6e351814965b9b5f1cd515994d6.html'], ['Meet in Shanghai', 'https://www.meet-in-shanghai.net/en/galleries/tank-shanghai-372520/']] }
];

const prompt = `Use case: scientific-educational\nAsset type: evidence-backed architectural cutaway plate\nPrimary request: Create an original through-the-walls architectural cutaway of [建筑名称] in [城市].\nEvidence packet: [来源链接或本地证据文件]. Do not depict a labelled feature unless it is verified in the claim ledger.\nVerified identity: [地点、年代、外观特征及来源].\nSection strategy: [轴测/纵剖/横剖] through [由证据支持的空间轴线].\nVerified key reveals: [结构+来源], [动线+来源], [主要空间+来源], [城市关系+来源].\nInference rule: for zones without direct documentation, create a plausible constrained reconstruction from verified exterior geometry, floor count, documented program, structural type, and comparable building type. Draw every inferred zone only with pale wash or fine hatching, visibly different from evidence-backed elements; never label it as fact.\nComposition: portrait 3:4, warm ivory paper background.\nStyle/medium: original precise pen-and-ink architectural linework with restrained watercolor wash.\nText: Title “[建筑名称]” and only verified Chinese callouts.\nConstraints: include a graphic legend for verified vs inferred reconstruction; no invented named rooms, exact plans, mechanisms, or structures; no logo, watermark, or photorealism.`;

document.querySelector('#prompt-text').textContent = prompt;
const gallery = document.querySelector('#gallery');
gallery.innerHTML = buildings.map((building, index) => `<article class="building building-${index + 1}"><button data-index="${index}" aria-label="放大查看${building.title}剖透图"><img src="${building.image}" loading="lazy" alt="${building.title}证据型建筑剖透图" /><span class="number">${building.no}</span></button><div><p>${building.type}</p><h3>${building.title}</h3><p>${building.detail}</p><p class="sources">来源：${building.sources.map(([name, href]) => `<a href="${href}" target="_blank" rel="noreferrer">${name}</a>`).join('、')}</p></div></article>`).join('');

const dialog = document.querySelector('#lightbox');
const img = document.querySelector('#lightbox-image');
const title = document.querySelector('#lightbox-title');
const number = document.querySelector('#lightbox-number');
const detail = document.querySelector('#lightbox-detail');
gallery.addEventListener('click', (event) => { const button = event.target.closest('button[data-index]'); if (!button) return; const building = buildings[button.dataset.index]; img.src = building.image; img.alt = `${building.title}证据型建筑剖透图`; title.textContent = building.title; number.textContent = `${building.no} / ${building.type}`; detail.textContent = building.detail; dialog.showModal(); });
document.querySelector('.close-button').addEventListener('click', () => dialog.close());
dialog.addEventListener('click', (event) => { if (event.target === dialog) dialog.close(); });
document.querySelector('.copy-button').addEventListener('click', async (event) => { await navigator.clipboard.writeText(prompt); event.target.textContent = '已复制'; setTimeout(() => { event.target.textContent = '复制 Prompt'; }, 1500); });
